---
driver:
  name: vagrant
  vagrantfiles: 
      - vagrantfile.rb

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.6
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[snapraid::default]
    attributes:
      snapraid:
        data_disks:
          - '/media/disk1/'
          - '/media/disk2/'
        parity_disks:
          - '/media/disk3/'
        content_files:
          - '/media/disk1/'
          - '/media/disk2/'